import type {
  ActivityType,
  ActivityMeta,
  Slot,
  MapPin,
  FlashDrop,
  NotificationItem,
  CityBadge,
  BumpRecord,
  MonthActivity,
  Organizer,
} from './types';

export const ACTIVITIES: ActivityMeta[] = [
  { type: 'coffee', emoji: '☕', label: 'Coffee', category: 'social' },
  { type: 'running', emoji: '🏃', label: 'Running', category: 'active' },
  { type: 'walk', emoji: '🚶', label: 'Walk', category: 'active' },
  { type: 'food', emoji: '🍽️', label: 'Food', category: 'food' },
  { type: 'drinks', emoji: '🍸', label: 'Drinks', category: 'social' },
  { type: 'sport', emoji: '⚽', label: 'Sport', category: 'active' },
  { type: 'yoga', emoji: '🧘', label: 'Yoga', category: 'active' },
  { type: 'cycling', emoji: '🚴', label: 'Cycling', category: 'active' },
  { type: 'photography', emoji: '📷', label: 'Photography', category: 'social' },
  { type: 'music', emoji: '🎵', label: 'Music', category: 'social' },
  { type: 'art', emoji: '🎨', label: 'Art', category: 'social' },
  { type: 'games', emoji: '🎮', label: 'Games', category: 'social' },
  { type: 'chess', emoji: '♟️', label: 'Chess', category: 'social' },
  { type: 'cowork', emoji: '💻', label: 'Co-work', category: 'social' },
  { type: 'networking', emoji: '🤝', label: 'Networking', category: 'social' },
  { type: 'study', emoji: '📚', label: 'Study', category: 'social' },
];

export const ACTIVITY_MAP: Record<ActivityType, ActivityMeta> =
  ACTIVITIES.reduce((acc, a) => {
    acc[a.type] = a;
    return acc;
  }, {} as Record<ActivityType, ActivityMeta>);

const organizers: Organizer[] = [
  { id: 'o1', name: 'Andriy Melnyk', username: '@andriy_m', avatarColor: '#FF2D35', initials: 'AM', reliability: 94 },
  { id: 'o2', name: 'Olena Kovalenko', username: '@olenak', avatarColor: '#3B82F6', initials: 'OK', reliability: 88 },
  { id: 'o3', name: 'Maksym Dmytrenko', username: '@maks_d', avatarColor: '#22C55E', initials: 'MD', reliability: 91 },
  { id: 'o4', name: 'Sofia Hrytsenko', username: '@sofia_g', avatarColor: '#F59E0B', initials: 'SH', reliability: 97 },
  { id: 'o5', name: 'Danylo Pavlenko', username: '@danylo_p', avatarColor: '#FF3B42', initials: 'DP', reliability: 85 },
  { id: 'o6', name: 'Viktoria Bondar', username: '@vika_b', avatarColor: '#EF4444', initials: 'VB', reliability: 90 },
];

export const SLOTS: Slot[] = [
  {
    id: 's1',
    activity: 'coffee',
    status: 'LIVE',
    title: 'Morning Espresso Run',
    description: 'Quick coffee before work. Trying a new roastery — join for a flat white and a chat.',
    location: 'Green Hills Coffee, Podil',
    area: 'Podil',
    timeLabel: 'Happening now',
    distanceKm: 0.4,
    organizer: organizers[0],
    capacity: 6,
    joined: 4,
    tags: ['coffee', 'morning', 'chill'],
    accessLevel: 'instant',
    happeningNow: true,
    startsInMinutes: 0,
  },
  {
    id: 's2',
    activity: 'running',
    status: 'OPEN',
    title: 'Evening Riverside Run',
    description: '5K along the Dnipro promenade. All paces welcome, we regroup at bridges.',
    location: 'Poshtova Square',
    area: 'Podil',
    timeLabel: 'Today · 18:30',
    distanceKm: 1.2,
    organizer: organizers[2],
    capacity: 12,
    joined: 7,
    tags: ['running', '5k', 'riverside'],
    accessLevel: 'instant',
    happeningNow: false,
    startsInMinutes: 180,
  },
  {
    id: 's3',
    activity: 'food',
    status: 'APPROVAL',
    title: 'Khachapuri & Wine Night',
    description: 'Georgian dinner at a hidden gem in Podil. 6 people, split the bill. Request to join.',
    location: 'Mimino Restaurant',
    area: 'Podil',
    timeLabel: 'Today · 19:00',
    distanceKm: 0.8,
    organizer: organizers[3],
    capacity: 6,
    joined: 4,
    tags: ['food', 'georgian', 'wine'],
    accessLevel: 'approval',
    happeningNow: false,
    startsInMinutes: 120,
  },
  {
    id: 's4',
    activity: 'photography',
    status: 'OPEN',
    title: 'Golden Hour Photo Walk',
    description: 'Capture the old town at sunset. Bring any camera, even a phone. We share tips after.',
    location: 'Andriyivskyy Descent',
    area: 'Old Town',
    timeLabel: 'Today · 17:45',
    distanceKm: 1.5,
    organizer: organizers[1],
    capacity: 8,
    joined: 3,
    tags: ['photography', 'sunset', 'walk'],
    accessLevel: 'instant',
    happeningNow: false,
    startsInMinutes: 90,
  },
  {
    id: 's5',
    activity: 'yoga',
    status: 'OPEN',
    title: 'Rooftop Sunrise Yoga',
    description: 'Vinyasa flow on a rooftop with a city view. Bring a mat, I\'ll bring the playlist.',
    location: 'Skyloft, Pechersk',
    area: 'Pechersk',
    timeLabel: 'Tomorrow · 06:30',
    distanceKm: 2.3,
    organizer: organizers[5],
    capacity: 10,
    joined: 6,
    tags: ['yoga', 'sunrise', 'rooftop'],
    accessLevel: 'approval',
    happeningNow: false,
    startsInMinutes: 1320,
  },
  {
    id: 's6',
    activity: 'chess',
    status: 'LIVE',
    title: 'Park Chess Blitz',
    description: 'Speed chess in the park. 5-minute games, loser passes the board. All levels.',
    location: 'Shevchenko Park',
    area: 'Centre',
    timeLabel: 'Happening now',
    distanceKm: 0.9,
    organizer: organizers[4],
    capacity: 8,
    joined: 5,
    tags: ['chess', 'park', 'blitz'],
    accessLevel: 'instant',
    happeningNow: true,
    startsInMinutes: 0,
  },
  {
    id: 's7',
    activity: 'drinks',
    status: 'OPEN',
    title: 'Cocktail Crawl · 3 Bars',
    description: 'Hit three speakeasies in one night. Start at Palata №6, end who-knows-where.',
    location: 'Palata №6',
    area: 'Old Town',
    timeLabel: 'Today · 21:00',
    distanceKm: 1.1,
    organizer: organizers[0],
    capacity: 8,
    joined: 6,
    tags: ['drinks', 'cocktails', 'nightlife'],
    accessLevel: 'approval',
    happeningNow: false,
    startsInMinutes: 300,
  },
  {
    id: 's8',
    activity: 'cycling',
    status: 'OPEN',
    title: 'City Night Ride',
    description: '15K loop through empty streets. Lights required, helmet recommended. Steady pace.',
    location: 'Maidan Nezalezhnosti',
    area: 'Centre',
    timeLabel: 'Today · 22:00',
    distanceKm: 1.0,
    organizer: organizers[2],
    capacity: 15,
    joined: 9,
    tags: ['cycling', 'night', 'urban'],
    accessLevel: 'instant',
    happeningNow: false,
    startsInMinutes: 360,
  },
];

export const MAP_PINS: MapPin[] = [
  { id: 'p1', slotId: 's1', x: 32, y: 40, activity: 'coffee', joined: 4, capacity: 6, status: 'LIVE' },
  { id: 'p2', slotId: 's2', x: 55, y: 28, activity: 'running', joined: 7, capacity: 12, status: 'OPEN' },
  { id: 'p3', slotId: 's3', x: 28, y: 62, activity: 'food', joined: 4, capacity: 6, status: 'APPROVAL' },
  { id: 'p4', slotId: 's4', x: 68, y: 50, activity: 'photography', joined: 3, capacity: 8, status: 'OPEN' },
  { id: 'p5', slotId: 's6', x: 48, y: 68, activity: 'chess', joined: 5, capacity: 8, status: 'LIVE' },
  { id: 'p6', slotId: 's7', x: 72, y: 35, activity: 'drinks', joined: 6, capacity: 8, status: 'OPEN' },
  { id: 'p7', slotId: 's8', x: 40, y: 22, activity: 'cycling', joined: 9, capacity: 15, status: 'OPEN' },
  { id: 'p8', slotId: 's5', x: 82, y: 60, activity: 'yoga', joined: 6, capacity: 10, status: 'OPEN' },
];

export const FLASH_DROPS: FlashDrop[] = [
  {
    id: 'f1',
    title: 'Flash Coffee · Free Round',
    emoji: '☕',
    location: 'Green Hills, Podil',
    distanceKm: 0.3,
    tags: ['coffee', 'flash', 'free'],
    secondsLeft: 842,
    joined: 3,
    capacity: 5,
  },
  {
    id: 'f2',
    title: 'Pop-up Skate Session',
    emoji: '🛹',
    location: 'Maidan Fountain',
    distanceKm: 0.9,
    tags: ['skate', 'flash', 'street'],
    secondsLeft: 1205,
    joined: 6,
    capacity: 12,
  },
  {
    id: 'f3',
    title: 'Instant Picnic · Bring Snacks',
    emoji: '🧺',
    location: 'Volodymyr Hill Park',
    distanceKm: 1.4,
    tags: ['picnic', 'park', 'chill'],
    secondsLeft: 534,
    joined: 4,
    capacity: 8,
  },
  {
    id: 'f4',
    title: 'Sunset Photo Sprint',
    emoji: '📷',
    location: 'River Overlook',
    distanceKm: 2.1,
    tags: ['photo', 'sunset', 'flash'],
    secondsLeft: 318,
    joined: 2,
    capacity: 6,
  },
  {
    id: 'f5',
    title: 'Night Market Food Walk',
    emoji: '🍢',
    location: 'Besarabsky Market',
    distanceKm: 1.7,
    tags: ['food', 'market', 'night'],
    secondsLeft: 1567,
    joined: 8,
    capacity: 15,
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    type: 'join',
    title: 'Andriy joined your slot',
    description: '"Morning Espresso Run" · 4 of 6 going',
    time: '2m ago',
    read: false,
  },
  {
    id: 'n2',
    type: 'approval',
    title: 'Approval needed',
    description: 'Sofia requested to join "Khachapuri & Wine Night"',
    time: '8m ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'reminder',
    title: 'Your slot starts soon',
    description: '"Evening Riverside Run" in 30 minutes',
    time: '12m ago',
    read: false,
  },
  {
    id: 'n4',
    type: 'bump',
    title: 'BUMP verified',
    description: 'You and Maksym met at "Park Chess Blitz"',
    time: '1h ago',
    read: true,
  },
  {
    id: 'n5',
    type: 'host',
    title: 'Your slot is live',
    description: '"Cocktail Crawl · 3 Bars" has 6 going',
    time: '3h ago',
    read: true,
  },
  {
    id: 'n6',
    type: 'system',
    title: 'City BPM rising',
    description: 'Podil activity is up 23% tonight',
    time: '5h ago',
    read: true,
  },
];

export const CITY_BADGES: CityBadge[] = [
  { city: 'Kyiv', country: 'Ukraine', flag: '🇺🇦', visits: 47 },
  { city: 'Lviv', country: 'Ukraine', flag: '🇺🇦', visits: 12 },
  { city: 'Cherkasy', country: 'Ukraine', flag: '🇺🇦', visits: 5 },
  { city: 'Odesa', country: 'Ukraine', flag: '🇺🇦', visits: 8 },
  { city: 'Warsaw', country: 'Poland', flag: '🇵🇱', visits: 3 },
  { city: 'Berlin', country: 'Germany', flag: '🇩🇪', visits: 2 },
];

export const BUMP_RECORDS: BumpRecord[] = [
  { id: 'b1', name: 'Maksym D.', event: 'Park Chess Blitz', date: 'Sep 6', verified: true },
  { id: 'b2', name: 'Olena K.', event: 'Golden Hour Photo Walk', date: 'Sep 4', verified: true },
  { id: 'b3', name: 'Sofia H.', event: 'Khachapuri & Wine Night', date: 'Sep 2', verified: true },
  { id: 'b4', name: 'Andriy M.', event: 'Morning Espresso Run', date: 'Aug 31', verified: true },
  { id: 'b5', name: 'Danylo P.', event: 'Park Chess Blitz', date: 'Aug 28', verified: true },
];

export const MONTH_ACTIVITY: MonthActivity[] = [
  { month: 'Apr', value: 3 },
  { month: 'May', value: 5 },
  { month: 'Jun', value: 7 },
  { month: 'Jul', value: 4 },
  { month: 'Aug', value: 9 },
  { month: 'Sep', value: 6 },
];

export const USER_PROFILE = {
  name: 'Yurii Tkachenko',
  username: '@yurii_t',
  initials: 'YT',
  avatarColor: '#FF2D35',
  city: 'Kyiv',
  area: 'Podil',
  reliability: 92,
  metrics: {
    showedUp: 38,
    hosted: 14,
    bumpVerified: 22,
    noShow: 1,
  },
  passport: {
    meetups: 52,
    cities: 6,
    hosted: 14,
  },
  interests: ['Coffee', 'Running', 'Photography', 'Chess', 'Cycling', 'Food', 'Yoga', 'Music'],
  isPlus: false,
};
